// Utilities
import { defineStore } from 'pinia'

export const useAppStore = defineStore('app', {
  state: () => ({
    snackbar: false,
    snackbarText: 'jknlkn;lkj;l',
    snackbarColor: 'indigo',
    categories: [
      'Actor',
      'Advertising Agency',
      'Airport Pickup',
      'Aluminium & Metallic Fabrication',
      'Animal Feed Processor',
      'Architect',
      'Artist (Fine and Applied)',
      'Bartender or Waiter or Waitress',
      'Bead Maker',
      'Birthdays',
      'Body Guard',
      'Borehole Drilling & Water Treatment',
      'Branding - Business or Personal',
      'Bricklayer & Mason',
      'Building Carpentry',
      'Building Engineer',
      'Business & Company Registration',
      'Business Branding',
      'Business Training and Consultancy',
      'Cake Baking', 'Car & Auto Repair',
      'Car & Personal Driver',
      'Car Air Conditioner (AC) Electrician',
      'Car and Auto Electrician',
      'Car Hire',
      'Car Painting',
      'Car Wash',
      'Carpenter & Furniture Maker',
      'Catering',
      'CCTV & Security Installation',
      'Chef',
      'Cloth Branding',
      'Comedian & MC',
      'Computer Centre & Cyber Cafe',
      'Computer Repairs',
      'Conference',
      'Content Writer & Editor',
      'Dancer',
      'Day Care',
      'Dentist',
      'Disc Jockey (DJ)',
      'Driving School',
      'Dry Cleaning',
      'DSTV & GOtv & Cable Technician',
      'Electronics Repair Electrician',
      'Epoxy Flooring',
      'Errand Boy or Girl',
      'Estate Agents',
      'Event & Wedding Rentals',
      'Event Cleaning',
      'Event Decoration',
      'Event Planner',
      'Extra Moral Classes',
      'Eye Doctor',
      'Fashion Class',
      'Fashion Designer',
      'Financial Auditor',
      'Food Delivery or Shopping',
      'Food Processing',
      'Fumigation & Pest Control',
      'Gardener',
      'Gardener',
      'Gele and Head Gear Tying',
      'Generator Repairs',
      'Graphics Designer & 3D Animation',
      'Gym and Fitness Trainer',
      'Herbalist or Traditional Doctor',
      'Home & Office Cleaning',
      'Home Wiring Electrician',
      'House painting',
      'House Roofing',
      'Industrial Machine Engineer',
      'Interior & Exterior Decoration',
      'Interpreter or Translator',
      'IT & Computer Class',
      'IT Services',
      'Job Vacancy',
      'Keke Repair',
      'Land Surveyor',
      'Language Class',
      'Lawyer & Legal Assistant',
      'Logistics & Delivery Services',
      'Maid & House Servant',
      'Makeup & Beauty Class',
      'Makeup Artist',
      'Manicurist & Pedicurist',
      'Manual Labour',
      'Manual Labour',
      'Massage and Spa',
      'Medical Doctor',
      'Medical Laboratory',
      'Medical Scan',
      'Men Salon & Barber',
      'Mobile Phone Repairs',
      'Model',
      'Motorcycle Repair',
      'Music & Movie Production',
      'Music Teachers',
      'Nanny and Baby Sitting',
      'Nursing & Midwifery',
      "Nurse",
      "Nutritionist or Dietitian",
      "Online Recharge and Subscription",
      "Other Domestic Services",
      "Other Educationals",
      "Other Estate Services",
      "Other Event Sevices",
      "Other Mechanical Services",
      "Other Mobile Services",
      "Other Services",
      "Other Taxi Services",
      "Others Auto Repairs",
      "Others Beauty Services",
      "Panel Beater", "Pharmacist",
      "Photography & Videography",
      "Plumbing",
      "POP Installation",
      "Presenter",
      "Printer",
      "Property Caretakers",
      "Property Lawyers",
      "Psychologist & Counselor",
      "Quantity Surveyor",
      "Quick Taxi",
      "Refrigerator and AC Repairs",
      "Sales Representative",
      "Secretary & Receptionist & Clerk",
      "Security or Gate Man",
      "Shipping & Freight Forwarding",
      "Shoe Maker or Cobbler",
      "Singer",
      "Social Media Manager",
      "Software Developer",
      "Solar & Inverter Installation",
      "Sound Engineer",
      "Special Subject Teachers",
      "Stamp & Award & Seal Maker",
      "Tailor",
      "Tile Installation",
      "Travel Agent",
      "Truck & Trailer Hire",
      "Trucks And Trailers Repair",
      "Usher & Event Staffing",
      "Veterinarian",
      "VIP Cab",
      "Vulcanizer",
      "Wall paper & 3D Wall panel Installation",
      "Web Designer & Developer",
      "Wedding",
      "Welding Fabrication",
      "Wheel Balancing and Alignment",
      "Women Salon & Hair Stylist"
    ]
  }),
})
